### ISSUE TITLE
Qestion; does this slicer support Dual extrusion /IDEX 3D printing

### ISSUE THREAD

**Issue by Voxel3DPrinting** [supermerill/SuperSlicer#1685]
Hi, 
Does the SuperSlicer software offer support for dual extrusion / IDEX? I am looking to change from Simplify3D, but CURA is just terrible for IDEX printing, but cannot find it anywhere.
Wondering if I can use it for my Xinkebot Orca 3 IDEX.
Hope to get a reaction,
Thanks, Sander

**Comment by Voxel3DPrinting** [comment]
Hi, Sorry for the late reply, had some issues with the printer.

I would really like if you would help me with this;

it is completely new for me but I think it should be;
{if next_extruder==1} G0 X-55 Y2400 {endif}
{if next_extruder==0} G0 X455 Y2400 {endif}
{if next_extruder==1}T{next_extruder}{endif}

S3D script;
{IF NEWTOOL=1}{IF OLDTOOL=0}G0 X-55 F2400
{IF NEWTOOL=0}{IF OLDTOOL=1}G0 X455 F2400
T[new_tool]

Is this true?

**Comment by supermerill** [comment]
> Is this true?

The third line shouln't have the `{if}{endif}`
The rest seems fine.
I advise you to check if, on a simple object, the `T` happens the same number of time. You may need to add a `{if current_layer >= 0}{endif}` to prevent it to trigger after the start-gcode.

**Comment by Voxel3DPrinting** [comment]
sir, this did not work..
What I want to accomplish is that if the tool used is the left one, the tool moves to X-55 after printing, if the tool used is the right one, it moves to X455 after use.

How do I get this?

**Comment by EddyMI3d** [comment]
If you run Marlin, that should be done on tool change by the firmware.

If you send T1 to the printer, T0 goes to X-55 (or whatever is set in the firmware)
If you send T0 to the printer, T1 goes to X455 (or whatever is set in the firmware)

**Comment by supermerill** [comment]
Working macro:
````
; park the old extruder
{if previous_extruder==0}G0 X455 Y2400{elsif previous_extruder==1}G0 X-55 Y2400{endif}
;change to the new
T{next_extruder}
;unpark it
{if next_extruder==0}G0 X400 Y2400{elsif next_extruder==1}G0 X0 Y2400{endif}
```
if you don't want to select & unpark at the print start, use
````
{if layer_num>=0}; park the old extruder
{if previous_extruder==0}G0 X455 Y2400{elsif previous_extruder==1}G0 X-55 Y2400{endif}
;change to the new
T{next_extruder}
;unpark it
{if next_extruder==0}G0 X400 Y2400{elsif next_extruder==1}G0 X0 Y2400{endif}{endif}
```

**Comment by Voxel3DPrinting** [comment]
Hey, thanks for the macros. If I slice a gcode file with it, the travel moves go somewhere to the backside?? they should be going to the sides?
How could I fix this? (see added image)

![Schermafbeelding 2021-11-10 225014](https://user-images.githubusercontent.com/73597964/141199284-ab0c84ff-5190-4729-be20-edb4f37e8f8a.jpg)

**Comment by supermerill** [comment]
on latest release?
if yes, give me your project file.

**Comment by Voxel3DPrinting** [comment]
It is from version 2.3.56.9.

Also, in your message Above with the scripts, the 2 gcode's are the same with anf without the park nozzle feature. Maybe this has to do with it?

**Comment by supermerill** [comment]
try with the new version, I fixed a bug of this kind.

> Maybe this has to do with it?

with what?

**Comment by Voxel3DPrinting** [comment]
Sir,
Problem persists with the newest firmware. project file attached here;https://we.tl/t-kHmsKnLnOC


I want to accomplish that old extruder goes to the side, and the new extruder continues printing.
If the old extruder is T0, it should move to X-55, if the old extruder is T1, it should move to X455. So far thankyou very much for your amazing help!

**Comment by supermerill** [comment]
I think it's because the slicer doesn't track the position of the extruder. For him, there is only one. So the preview can't be what's going on IRL.

Have to check & see if I can fix that.

**Comment by Voxel3DPrinting** [comment]
Hi @supermerill 

Been a while and learned C++ programming in the meantime. I reprogrammed the script and it works correctly now. Thanks again for your help 1,5 years ago!
