### ISSUE TITLE
Artifacts with spiral vase on a cube of about 20 mm

### ISSUE THREAD

**Issue by liftbag** [supermerill/SuperSlicer#2114]
**Bug description**
It is a strange behavior, as it is highlighted in different ways depending on the size of the cube. However, it appears only with measurements close to 20mm per side. It is not present in PrusaSlicer.
To make sure I don't have wrong settings, I set a Prusa printer, a standard prusament PLA filament and 0.20mm QUALITY Print settings.
The defect consists in a misalignment in one extrusion line of the walls of the cube at a variable height based on the size of the cube.

**Expected behavior**
Walls with all layers perfectly aligned.

!!>> Project File <<!!
[Shape-Box.3mf.zip](https://github.com/supermerill/SuperSlicer/files/7773470/Shape-Box.3mf.zip)

**To Reproduce**
1. Open the slicer
2. Right click > Add Shape Box or open a 20mm cube file
3. Set Spiral vase to on.
4. Slice and look for misaligned extrusions
5. Eventually change the measures of the cube in a range between 19 and 21mm and observe the misalignments that occur at different heights

**Screenshots**
21mm shape box
<img width="1509" alt="Schermata 2021-12-24 alle 09 35 42" src="https://user-images.githubusercontent.com/14921654/147336056-04a7b10f-e955-4e19-9045-aa40827617a1.png">

20mm shape box
<img width="1509" alt="Schermata 2021-12-24 alle 09 33 51" src="https://user-images.githubusercontent.com/14921654/147336105-a5c55e83-f42c-4fd3-b267-93f84493cde0.png">

19mm shape box
<img width="1509" alt="Schermata 2021-12-24 alle 09 33 17" src="https://user-images.githubusercontent.com/14921654/147336141-cd7a8aef-7f77-4c66-9a55-012cf1b9f0a3.png">

**Desktop (please complete the following information):**
OS:
<img width="698" alt="Schermata 2021-12-24 alle 09 45 42" src="https://user-images.githubusercontent.com/14921654/147336791-e7218f0b-a344-40ea-b5c4-edb777439f97.png">

 - Version: "fix filament override & gapfill NaN" macos 448
 - Printer model: any

**Comment by sajmonSK** [comment]
It also exhibits this weird volumetric rate decrease on one side, and the build from 20th december did not do this,
![Screenshot 2021-12-27 120610](https://user-images.githubusercontent.com/95093887/147466286-986785c7-a77c-4287-8a96-4c0ed2be3038.png)

**Comment by liftbag** [comment]
> It also exhibits this weird volumetric rate decrease on one side, and the build from 20th december did not do this, ![Screenshot 2021-12-27 120610](https://user-images.githubusercontent.com/95093887/147466286-986785c7-a77c-4287-8a96-4c0ed2be3038.png)

I can confirm.
![IMG_2839](https://user-images.githubusercontent.com/14921654/147470007-f1a1b14e-34dc-4baa-b2d7-d3b4ea2c124a.jpg)

**Comment by liftbag** [comment]
Fixed both artifacts and volumetric rate in the latest nightly. Thanks merill 👍

**Comment by batista16** [comment]
This did not fix all the issues I have with vase mode: 
![image](https://user-images.githubusercontent.com/6854591/147960924-86896df9-2d23-463d-8f2c-8b583c9b808a.png)
[low-poly-pot-designed-by-additae.zip](https://github.com/supermerill/SuperSlicer/files/7803216/low-poly-pot-designed-by-additae.zip)

**Comment by supermerill** [comment]
@batista16 that is an artefact of the process. Can't remove it without specialised slicing (it's because it's slopped: the spiral move the position a bit , and so it's not on the object polygon anymore is there is a slope)
I'll modify the spiral start code to allow you to set the seam position, so you can choose the best start position for it, like the back.

**Comment by batista16** [comment]
humm.. 
I think the seam position will not help in every scenario.. there's round objects.. 
I thought that the Spiral Vase entire goal was to have no seam, increasing the Z a full layer height for every layer. 
Cura doesn't have this issue (Although, it has many, many more..), just mentioning cura because they must have solved it somehow right? 

And I have other examples that don't look related to seam, because they are horizontal:
![image](https://user-images.githu
[Craquelado 12x10.zip](https://github.com/supermerill/SuperSlicer/files/7810663/Craquelado.12x10.zip)
busercontent.com/6854591/148130347-edfd8892-6086-4364-ad93-9b2effec1486.png)

**Comment by supermerill** [comment]
@batista16 I don't see any problem on this one at the first look.

**Comment by supermerill** [comment]
found the issue: there is some detrimental geometry hidden inside the object:
![image](https://user-images.githubusercontent.com/6536403/148137871-f4ab3271-4613-4de6-b215-5b42344b7807.png)

**Comment by batista16** [comment]
Ok, Back to the first example: 
![image](https://user-images.githubusercontent.com/6854591/148207292-4f4d3195-7c7f-4542-8da5-26ed3a65031d.png)
On Cura:
![image](https://user-images.githubusercontent.com/6854591/148207344-7ee2e980-0613-41a3-b7ba-05b5e42109fb.png)
[lowpolypot.zip](https://github.com/supermerill/SuperSlicer/files/7814370/lowpolypot.zip)

On this case is completely round, so adjusting the seam position will not solve the issue..

**Comment by supermerill** [comment]
can't do much more unless I want to redo entirely the thing.
It slices it in the slope but when moving it up, it jumps over the edge, that's why it is shown as misplaced.
