### ISSUE TITLE
Seams on overhangs are non-continues when using threshold modifier for overhang speed and flow

### ISSUE THREAD

**Issue by Trini8ed** [supermerill/SuperSlicer#3727]
### What happened?

When use the threshold modifier for overhangs, seams are incorrectly placed compared to when its disabled.

This issue is explicitly for how the seam becomes disjoint when encountering the modifier for overhangs. Please ignore the fact its not a straight line for aligned that is another issue.

### Project file & How to reproduce

1. Open attached STL in a new SS scene, make sure seams are aligned
2. Make sure these settings are enabled. under threshold for
![image](https://user-images.githubusercontent.com/1361448/225189343-ae3d2469-544a-4527-9012-92f5766df79b.png)
4. Slice the part
5. Enable seams to show
6. Expect the following result
![image](https://user-images.githubusercontent.com/1361448/225190357-7f167d4a-b6d7-4f9d-bf3f-9269d9be08f6.png)

[Shape-Sphere.zip](https://github.com/supermerill/SuperSlicer/files/10975473/Shape-Sphere.zip)

### Version

2.4.58.4,2.5.59.2

### Operating system

Windows 11

### Printer model

prusa mk3s

**Comment by pajtaz** [comment]
The aligned seam works in 2.5.59.2 on the one model I am testing but does not work on any version after that if the threshold modifier for overhangs is on. I really need a fix for this for the latest 2.5.59.8, it's driving me insane.

**Comment by supermerill** [comment]
Can't reproduce, can I have your project file, and not only the stl?
![image](https://github.com/supermerill/SuperSlicer/assets/6536403/6535c28c-407a-4636-a1a9-e5e0cd8ee48c)

**Comment by Trini8ed** [comment]
Looks like this has been resolved as of 59.9, the main thing this ticket was about was making sure that when the overhang threshold was applied the seam locations would be the same as they were with it off.

![image](https://github.com/supermerill/SuperSlicer/assets/1361448/c99f5f83-0b95-4eae-be8a-e49e412de791)

**Comment by pajtaz** [comment]
This is not resolved and in general there is a problem with overhang seams. I have attached 3MF file. You can see in the sliced preview that there is no seam shown on the external overhang wall while there is a seam shown on the external non-overhang wall. It is a huge problem when printing, as you can see in the third photo of the actual print with these settings. Seam is massive and ugly only on the overhang wall. I am using 30% overhang threshold so these walls would be printed slow enough and with enough cooling so they don't droop.
![No seam shown on external overhang wall](https://github.com/supermerill/SuperSlicer/assets/19250632/b694997f-ef4f-415f-8647-df40bb16fecd)
![Seam shown only on the other external non-overhang wall](https://github.com/supermerill/SuperSlicer/assets/19250632/9929158e-3d5d-
[Bad overhang seam.zip](https://github.com/supermerill/SuperSlicer/files/15285326/Bad.overhang.seam.zip)
45e5-843f-cab449d33474)
![Ugly seam on external overhang wall](https://github.com/supermerill/SuperSlicer/assets/19250632/1fc0decf-aed8-4704-b84b-823d263c2c57)

**Comment by legend069** [comment]
seam placement should be avoided on curved corners like that as pressure advance tends to mess with it.

**Comment by supermerill** [comment]
I changed the seam formula, so overhangs aren't evicted if the overhangs is very small or if there is only overhangs.
Seems like the behaviour is better. 
![image](https://github.com/supermerill/SuperSlicer/assets/6536403/9aaf5d10-3462-4ddf-b81b-3ef5c8cbc26e)
(huge seam gap to highlight them)

**Comment by pajtaz** [comment]
Ok, I will test this at some point. For now I mitigated the problem by setting the overhang threshold do 30% instead of 25% (that made most previously identified overhangs as normal perimeters so this issue was not present).

**Comment by Bunadaj801** [comment]
Hi, can I also emphasize how big an issue this is. I love ss and have switched from prusa but this issue is ruining my print quality. If I want control over my seams I have to disable overhang detection and have poor looking overhangs. So I have to choose, ugly seam placement or ugly overhangs. It's a shame as this isn't an issue in other slicers. Hope this gets resolved and would put this high on the priority list.
