### ISSUE TITLE
Layer time goal not working

### ISSUE THREAD

**Issue by trampas** [supermerill/SuperSlicer#4053]
### What happened?

The layer time goal setting in "filament settings" are not working. 
<img width="884" alt="Screenshot 2024-01-04 134120" src="https://github.com/supermerill/SuperSlicer/assets/6846781/ac6a73cb-ae78-4978-91d3-71e98b9ed318">
<img width="854" alt="Screenshot 2024-01-04 134213" src="https://github.com/supermerill/SuperSlicer/assets/6846781/fa74984e-2745-4c0c-966c-a1e565bef763">

The images above show that the layer time goal should be 100s 
<img width="823" alt="Screenshot 2024-01-04 134308" src="https://github.com/supermerill/SuperSlicer/assets/6846781/30f4ff39-6060-4d02-a746-8102666b1ad3">

The speed never reaches 5mm/s as requested 

### Project file & How to reproduce

Open the zip file and project and give it a try yourself 
[elevators_2hr.zip](https://github.com/supermerill/SuperSlicer/files/13834321/elevators_2hr.zip)

### Version

2.5.59

### Operating system

windows 11

### Printer model

voron 2.4 with stealthburn

**Comment by supermerill** [comment]
can't reproduce on 2.5.59.6
if you go to help -> about, what is your version?

**Comment by trampas** [comment]
It is 2.5.59.

It appears to work in prusaslicer 2.7.x

I assume it is a PS bug that was fixed. Also parameters for the feature is different in PS 2.7.

**Comment by Murrdo** [comment]
At the moment, the bug is fixed in 2.5.59 (Win10 - the latest nightly build), I've been waiting for it to be fixed for a very long time)

**Comment by supermerill** [comment]
there was also a bug in 59.4 and prior, fixed in .5 and .6
https://github.com/supermerill/SuperSlicer/issues/4015
that's why i want to know your full 4-digit version

**Comment by trampas** [comment]
Mine is 2.5.59.3

**Comment by ercdvs** [comment]
I am on 2.5.59.6 and I still have this issue.  In my understanding,  The top most layer should be 15s, but are currently 1s

![image](https://github.com/supermerill/SuperSlicer/assets/6096665/388c2103-7ede-4111-bb48-00891b87eb95)

![image](https://github.com/supermerill/SuperSlicer/assets/6096665/40f40ad9-ecfc-4f7a-9f19-77908321ab65)


![image](https://github.com/supermerill/SuperSlicer/assets/6096665/7cc53a15-bcf1-4477-8490-c9ee1c570a6b)

**Comment by supermerill** [comment]
@ercdvs i need your project file to test myself, to reproduce and fix.

**Comment by ercdvs** [comment]
> @ercdvs i need your project file to test myself, to reproduce and fix.

Added to my original comment

**Comment by supermerill** [comment]
On 2.5.59.6
![image](https://github.com/supermerill/SuperSlicer/assets/6536403/41a95d55-6bc1-480f-98d2-1845d584a002)
the only parts where it goes below 15sec is when it's at the very top.

**Comment by supermerill** [comment]
use `layer time (log)` (the second one) to have a better scale

**Comment by Nerobeus** [comment]
I found away to reproduce, it happen when changing any speed for print move in print settings and can't be reverted without loading a previous saved project or delete all profiles.
