### ISSUE TITLE
Vase mode create an unwanted line

### ISSUE THREAD

**Issue by Zunzulla** [supermerill/SuperSlicer#719]
### Version
2.2.53
### Operating system type + version
Microsoft Windows 10 Pro 10.0.19041

### 3D printer brand / version + firmware version (if known)
Prusa MK3S 1.2mm nozzle

### Behavior
When slicing a circular object in vase mode with concentric (filled) infill, the gap fill appears to be misplaced

#### Project File (.3MF) where problem occurs

![issue1](https://user-images.githubusercontent.com/48380992/100250826-61c96b00-2f3e-11eb-9254-b94900c741a3.png)
![20201125_164944](https://user-images.githubusercontent.com/48380992/100250878-7148b400-2f3e-11eb-9cbf-a36486eb12da.jpg)

[Concentric(filled)IssueGapFill.zip](https://github.com/supermerill/SuperSlicer/files/5597739/Concentric.filled.IssueGapFill.zip)

**Comment by Zunzulla** [comment]
Adding to this: using the concentric (filled) infill (same settings as in the project file posted before) on a square object, the center part is not filled. The gap fill only happens on one line, instead of all 4 
![issue2](https://user-images.githubusercontent.com/48380992/100375209-bab40480-300d-11eb-98b2-b39de857e86e.png)

**Comment by Zunzulla** [comment]
Adding the file 
[SquareConcentric(filled)IssueGapFill.zip](https://github.com/supermerill/SuperSlicer/files/5604213/SquareConcentric.filled.IssueGapFill.zip)

**Comment by supermerill** [comment]
fixed in 2.3.55, have to port it back to the stable branch.

**Comment by Zunzulla** [comment]
> fixed in 2.3.55, have to port it back to the stable branch.

Sorry, didn't understand ^^ I tried slicing with the latest stable branch and 2.3.55, the gap fill still gets misplaced

**Comment by supermerill** [comment]
Oh, it's a vase mode bug
